language: d

d:
  # order: latest DMD, oldest DMD, LDC/GDC, remaining DMD versions
  # this way the overall test time gets cut down (GDC/LDC are a lot
  # slower tham DMD, so they should be started early), while still
  # catching most DMD version related build failures early
  - dmd-2.075.0
  - dmd-2.071.2
  - ldc-1.3.0
  - ldc-1.2.0
  - ldc-1.1.0
  - dmd-2.074.1
  - dmd-2.073.2
  - dmd-2.072.2
  - dmd-beta

env:
    - CONFIG=select
    - CONFIG=epoll
    # disabled until the libasync driver of eventcore is more than a stub
    #- CONFIG=libasync

matrix:
  allow_failures:
    - env: CONFIG=libasync
    - d: dmd-beta
  include:
    - d: dmd
      env: CONFIG='select' DUB_FLAGS='--build unittest-cov --build-mode=singleFile'
    - d: dmd
      env: CONFIG='select' DUB_FLAGS='--build unittest-cov --build-mode=singleFile'
    - d: dmd
      env: CONFIG='select' DUB_FLAGS='--build unittest-cov --build-mode=singleFile'

script: ./travis-ci.sh

sudo: false

after_success:
 - bash <(curl -s https://codecov.io/bash)
